drop table if exists app_dictionary;
create table app_dictionary
(
    id          int generated by default as identity primary key,
    type        varchar(30),
    status      int         not null,
    name        varchar(30) not null,
    create_time timestamp(0) default now()
);

comment on table app_dictionary is '字典表';
comment on column app_dictionary.type is '字典类别';
comment on column app_dictionary.status is '字典状态值';
comment on column app_dictionary.name is '字典名称';
comment on column app_dictionary.create_time is '创建时间';

-- 初始化字典表
insert into app_dictionary(type, status, name)
values ('notify', 1, 'info');

insert into app_dictionary(type, status, name)
values ('notify', 2, 'success');

insert into app_dictionary(type, status, name)
values ('notify', 3, 'warning');

insert into app_dictionary(type, status, name)
values ('notify', 4, 'error');

insert into app_dictionary(type, status, name)
values ('notify', 5, '已处理');

insert into app_dictionary(type, status, name)
values ('notify', 6, '未处理');

insert into app_dictionary(type, status, name)
values ('user', 0, '男');

insert into app_dictionary(type, status, name)
values ('user', 1, '女');

insert into app_dictionary(type, status, name)
values ('tool', 1, '路由工具');

insert into app_dictionary(type, status, name)
values ('tool', 2, '窗口工具');

insert into app_dictionary(type, status, name)
values ('tool_position', 1, '左侧');

insert into app_dictionary(type, status, name)
values ('tool_position', 2, '右侧');

insert into app_dictionary(type, status, name)
values ('chat_knowledge_file', 1, '文件夹');

insert into app_dictionary(type, status, name)
values ('chat_knowledge_file', 2, 'docx');

insert into app_dictionary(type, status, name)
values ('chat_knowledge_file', 3, 'pdf');

insert into app_dictionary(type, status, name)
values ('chat_knowledge_file', 4, 'excel');

insert into app_dictionary(type, status, name)
values ('chat_knowledge_file', 5, 'txt');


-- 消息表
drop table if exists app_notify;
create table app_notify
(
    id          varchar(30) primary key,
    pub_id      varchar(30)  not null,
    sub_id      varchar(30)  not null,
    title       varchar(50)  not null,
    msg_type    int          default 0,
    type        int          default 0,
    text        varchar(500) not null,
    param       json         default '{}',
    template    varchar(500) default 'DefaultNotifyBody',
    status      int          default 0,
    is_delete   int          default 0,
    create_time timestamp(0) default now(),
    update_time timestamp(0) default now()
);
comment on table app_notify is '消息通知表';
comment on column app_notify.pub_id is '生产者';
comment on column app_notify.sub_id is '消费者';
comment on column app_notify.title is '消息标题';
comment on column app_notify.msg_type is '消息类型 1:info 2:success 3:warning 4:error';
comment on column app_notify.type is '消息类别 0:普通文本消息';
comment on column app_notify.text is '消息文本';
comment on column app_notify.param is '消息上下文参数';
comment on column app_notify.template is '消息模板组件';
comment on column app_notify.status is '消息状态 0:未处理 1:已处理';
comment on column app_notify.is_delete is '是否删除';
comment on column app_notify.create_time is '创建时间';
comment on column app_notify.update_time is '处理时间';




drop table if exists app_setting;
create table app_setting
(
    id          varchar(30) primary key,
    pid         varchar(30)  not null,
    user_id     varchar(30)  not null,
    name        varchar(100) not null,
    value       varchar(500) not null,
    tool_id     varchar(30)  not null,
    setting     json                  default '{}',
    create_time timestamp(0) not null default now()
);
comment on table app_setting is 'app 设置表';
comment on column app_setting.id is '设置id';
comment on column app_setting.pid is '父id';
comment on column app_setting.user_id is '所属用户';
comment on column app_setting.name is '设置项名';
comment on column app_setting.value is '设置项展示组件名';
comment on column app_setting.tool_id is '配置所属工具id';
comment on column app_setting.setting is '设置属性值';





